//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.18444
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrazabilidadCarne.Test.TrazabilidadCarnesService {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TrazabilidadCarnesService.IBarra")]
    public interface IBarra {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarra/ProcesaBarras", ReplyAction="http://tempuri.org/IBarra/ProcesaBarrasResponse")]
        TrazabilidadCarne.Services.ResultadoProceso ProcesaBarras(string barra1, string barra2, string codigoLocal);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarra/ObtieneItemBalanza", ReplyAction="http://tempuri.org/IBarra/ObtieneItemBalanzaResponse")]
        TrazabilidadCarne.Services.EntidadItem[] ObtieneItemBalanza();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarra/ObtieneProcedencia", ReplyAction="http://tempuri.org/IBarra/ObtieneProcedenciaResponse")]
        TrazabilidadCarne.Services.EntidadProcedencia[] ObtieneProcedencia();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarra/ObtieneFrigorificos", ReplyAction="http://tempuri.org/IBarra/ObtieneFrigorificosResponse")]
        TrazabilidadCarne.Services.EntidadFrigorifico[] ObtieneFrigorificos();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarra/ObtieneParidades", ReplyAction="http://tempuri.org/IBarra/ObtieneParidadesResponse")]
        TrazabilidadCarne.Services.EntidadParidad[] ObtieneParidades();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IBarra/ProcesaBarrasMSG", ReplyAction="http://tempuri.org/IBarra/ProcesaBarrasMSGResponse")]
        TrazabilidadCarne.Services.ResultadoProceso ProcesaBarrasMSG(string Mensaje, string codigoLocal);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IBarraChannel : TrazabilidadCarne.Test.TrazabilidadCarnesService.IBarra, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class BarraClient : System.ServiceModel.ClientBase<TrazabilidadCarne.Test.TrazabilidadCarnesService.IBarra>, TrazabilidadCarne.Test.TrazabilidadCarnesService.IBarra {
        
        public BarraClient() {
        }
        
        public BarraClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public BarraClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BarraClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public BarraClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public TrazabilidadCarne.Services.ResultadoProceso ProcesaBarras(string barra1, string barra2, string codigoLocal) {
            return base.Channel.ProcesaBarras(barra1, barra2, codigoLocal);
        }
        
        public TrazabilidadCarne.Services.EntidadItem[] ObtieneItemBalanza() {
            return base.Channel.ObtieneItemBalanza();
        }
        
        public TrazabilidadCarne.Services.EntidadProcedencia[] ObtieneProcedencia() {
            return base.Channel.ObtieneProcedencia();
        }
        
        public TrazabilidadCarne.Services.EntidadFrigorifico[] ObtieneFrigorificos() {
            return base.Channel.ObtieneFrigorificos();
        }
        
        public TrazabilidadCarne.Services.EntidadParidad[] ObtieneParidades() {
            return base.Channel.ObtieneParidades();
        }
        
        public TrazabilidadCarne.Services.ResultadoProceso ProcesaBarrasMSG(string Mensaje, string codigoLocal) {
            return base.Channel.ProcesaBarrasMSG(Mensaje, codigoLocal);
        }
    }
}
