//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

using System;
using System.ComponentModel;
using System.Data.EntityClient;
using System.Data.Objects;
using System.Data.Objects.DataClasses;
using System.Linq;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
namespace TrazabilidadCarne.Services.Datos
{
    #region Contextos
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    public partial class GestionContenedor : ObjectContext
    {
        #region Constructores
    
        /// <summary>
        /// Inicializa un nuevo objeto GestionContenedor usando la cadena de conexión encontrada en la sección 'GestionContenedor' del archivo de configuración de la aplicación.
        /// </summary>
        public GestionContenedor() : base("name=GestionContenedor", "GestionContenedor")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto GestionContenedor.
        /// </summary>
        public GestionContenedor(string connectionString) : base(connectionString, "GestionContenedor")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        /// <summary>
        /// Inicializar un nuevo objeto GestionContenedor.
        /// </summary>
        public GestionContenedor(EntityConnection connection) : base(connection, "GestionContenedor")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }
    
        #endregion
    
        #region Métodos parciales
    
        partial void OnContextCreated();
    
        #endregion
    
        #region Propiedades de ObjectSet
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        public ObjectSet<vw_DM_LOCAL> vw_DM_LOCAL
        {
            get
            {
                if ((_vw_DM_LOCAL == null))
                {
                    _vw_DM_LOCAL = base.CreateObjectSet<vw_DM_LOCAL>("vw_DM_LOCAL");
                }
                return _vw_DM_LOCAL;
            }
        }
        private ObjectSet<vw_DM_LOCAL> _vw_DM_LOCAL;

        #endregion

        #region Métodos AddTo
    
        /// <summary>
        /// Método desusado para agregar un nuevo objeto al EntitySet vw_DM_LOCAL. Considere la posibilidad de usar el método .Add de la propiedad ObjectSet&lt;T&gt; asociada.
        /// </summary>
        public void AddTovw_DM_LOCAL(vw_DM_LOCAL vw_DM_LOCAL)
        {
            base.AddObject("vw_DM_LOCAL", vw_DM_LOCAL);
        }

        #endregion

    }

    #endregion

    #region Entidades
    
    /// <summary>
    /// No hay documentación de metadatos disponible.
    /// </summary>
    [EdmEntityTypeAttribute(NamespaceName="GestionModel", Name="vw_DM_LOCAL")]
    [Serializable()]
    [DataContractAttribute(IsReference=true)]
    public partial class vw_DM_LOCAL : EntityObject
    {
        #region Método de generador
    
        /// <summary>
        /// Crear un nuevo objeto vw_DM_LOCAL.
        /// </summary>
        /// <param name="lOCAL_ID">Valor inicial de la propiedad LOCAL_ID.</param>
        /// <param name="mERCADO_ID">Valor inicial de la propiedad MERCADO_ID.</param>
        /// <param name="fORMATO_ID">Valor inicial de la propiedad FORMATO_ID.</param>
        /// <param name="cIUDAD_ID">Valor inicial de la propiedad CIUDAD_ID.</param>
        /// <param name="rEGION_ID">Valor inicial de la propiedad REGION_ID.</param>
        /// <param name="pAIS_ID">Valor inicial de la propiedad PAIS_ID.</param>
        public static vw_DM_LOCAL Createvw_DM_LOCAL(global::System.Decimal lOCAL_ID, global::System.Decimal mERCADO_ID, global::System.Decimal fORMATO_ID, global::System.Decimal cIUDAD_ID, global::System.Decimal rEGION_ID, global::System.Decimal pAIS_ID)
        {
            vw_DM_LOCAL vw_DM_LOCAL = new vw_DM_LOCAL();
            vw_DM_LOCAL.LOCAL_ID = lOCAL_ID;
            vw_DM_LOCAL.MERCADO_ID = mERCADO_ID;
            vw_DM_LOCAL.FORMATO_ID = fORMATO_ID;
            vw_DM_LOCAL.CIUDAD_ID = cIUDAD_ID;
            vw_DM_LOCAL.REGION_ID = rEGION_ID;
            vw_DM_LOCAL.PAIS_ID = pAIS_ID;
            return vw_DM_LOCAL;
        }

        #endregion

        #region Propiedades primitivas
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal LOCAL_ID
        {
            get
            {
                return _LOCAL_ID;
            }
            set
            {
                if (_LOCAL_ID != value)
                {
                    OnLOCAL_IDChanging(value);
                    ReportPropertyChanging("LOCAL_ID");
                    _LOCAL_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("LOCAL_ID");
                    OnLOCAL_IDChanged();
                }
            }
        }
        private global::System.Decimal _LOCAL_ID;
        partial void OnLOCAL_IDChanging(global::System.Decimal value);
        partial void OnLOCAL_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LOCAL_COD
        {
            get
            {
                return _LOCAL_COD;
            }
            set
            {
                OnLOCAL_CODChanging(value);
                ReportPropertyChanging("LOCAL_COD");
                _LOCAL_COD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LOCAL_COD");
                OnLOCAL_CODChanged();
            }
        }
        private global::System.String _LOCAL_COD;
        partial void OnLOCAL_CODChanging(global::System.String value);
        partial void OnLOCAL_CODChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LOCAL_DESC
        {
            get
            {
                return _LOCAL_DESC;
            }
            set
            {
                OnLOCAL_DESCChanging(value);
                ReportPropertyChanging("LOCAL_DESC");
                _LOCAL_DESC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LOCAL_DESC");
                OnLOCAL_DESCChanged();
            }
        }
        private global::System.String _LOCAL_DESC;
        partial void OnLOCAL_DESCChanging(global::System.String value);
        partial void OnLOCAL_DESCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String LOCAL_DESC_COMPL
        {
            get
            {
                return _LOCAL_DESC_COMPL;
            }
            set
            {
                OnLOCAL_DESC_COMPLChanging(value);
                ReportPropertyChanging("LOCAL_DESC_COMPL");
                _LOCAL_DESC_COMPL = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("LOCAL_DESC_COMPL");
                OnLOCAL_DESC_COMPLChanged();
            }
        }
        private global::System.String _LOCAL_DESC_COMPL;
        partial void OnLOCAL_DESC_COMPLChanging(global::System.String value);
        partial void OnLOCAL_DESC_COMPLChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> LOCAL_TIPO_ID
        {
            get
            {
                return _LOCAL_TIPO_ID;
            }
            set
            {
                OnLOCAL_TIPO_IDChanging(value);
                ReportPropertyChanging("LOCAL_TIPO_ID");
                _LOCAL_TIPO_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("LOCAL_TIPO_ID");
                OnLOCAL_TIPO_IDChanged();
            }
        }
        private Nullable<global::System.Decimal> _LOCAL_TIPO_ID;
        partial void OnLOCAL_TIPO_IDChanging(Nullable<global::System.Decimal> value);
        partial void OnLOCAL_TIPO_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> CADENA_ID
        {
            get
            {
                return _CADENA_ID;
            }
            set
            {
                OnCADENA_IDChanging(value);
                ReportPropertyChanging("CADENA_ID");
                _CADENA_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("CADENA_ID");
                OnCADENA_IDChanged();
            }
        }
        private Nullable<global::System.Decimal> _CADENA_ID;
        partial void OnCADENA_IDChanging(Nullable<global::System.Decimal> value);
        partial void OnCADENA_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal MERCADO_ID
        {
            get
            {
                return _MERCADO_ID;
            }
            set
            {
                if (_MERCADO_ID != value)
                {
                    OnMERCADO_IDChanging(value);
                    ReportPropertyChanging("MERCADO_ID");
                    _MERCADO_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("MERCADO_ID");
                    OnMERCADO_IDChanged();
                }
            }
        }
        private global::System.Decimal _MERCADO_ID;
        partial void OnMERCADO_IDChanging(global::System.Decimal value);
        partial void OnMERCADO_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MERCADO_COD
        {
            get
            {
                return _MERCADO_COD;
            }
            set
            {
                OnMERCADO_CODChanging(value);
                ReportPropertyChanging("MERCADO_COD");
                _MERCADO_COD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MERCADO_COD");
                OnMERCADO_CODChanged();
            }
        }
        private global::System.String _MERCADO_COD;
        partial void OnMERCADO_CODChanging(global::System.String value);
        partial void OnMERCADO_CODChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String MERCADO_DESC
        {
            get
            {
                return _MERCADO_DESC;
            }
            set
            {
                OnMERCADO_DESCChanging(value);
                ReportPropertyChanging("MERCADO_DESC");
                _MERCADO_DESC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("MERCADO_DESC");
                OnMERCADO_DESCChanged();
            }
        }
        private global::System.String _MERCADO_DESC;
        partial void OnMERCADO_DESCChanging(global::System.String value);
        partial void OnMERCADO_DESCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal FORMATO_ID
        {
            get
            {
                return _FORMATO_ID;
            }
            set
            {
                if (_FORMATO_ID != value)
                {
                    OnFORMATO_IDChanging(value);
                    ReportPropertyChanging("FORMATO_ID");
                    _FORMATO_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("FORMATO_ID");
                    OnFORMATO_IDChanged();
                }
            }
        }
        private global::System.Decimal _FORMATO_ID;
        partial void OnFORMATO_IDChanging(global::System.Decimal value);
        partial void OnFORMATO_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FORMATO_COD
        {
            get
            {
                return _FORMATO_COD;
            }
            set
            {
                OnFORMATO_CODChanging(value);
                ReportPropertyChanging("FORMATO_COD");
                _FORMATO_COD = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FORMATO_COD");
                OnFORMATO_CODChanged();
            }
        }
        private global::System.String _FORMATO_COD;
        partial void OnFORMATO_CODChanging(global::System.String value);
        partial void OnFORMATO_CODChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public global::System.String FORMATO_DESC
        {
            get
            {
                return _FORMATO_DESC;
            }
            set
            {
                OnFORMATO_DESCChanging(value);
                ReportPropertyChanging("FORMATO_DESC");
                _FORMATO_DESC = StructuralObject.SetValidValue(value, true);
                ReportPropertyChanged("FORMATO_DESC");
                OnFORMATO_DESCChanged();
            }
        }
        private global::System.String _FORMATO_DESC;
        partial void OnFORMATO_DESCChanging(global::System.String value);
        partial void OnFORMATO_DESCChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=false, IsNullable=true)]
        [DataMemberAttribute()]
        public Nullable<global::System.Decimal> COMUNA_ID
        {
            get
            {
                return _COMUNA_ID;
            }
            set
            {
                OnCOMUNA_IDChanging(value);
                ReportPropertyChanging("COMUNA_ID");
                _COMUNA_ID = StructuralObject.SetValidValue(value);
                ReportPropertyChanged("COMUNA_ID");
                OnCOMUNA_IDChanged();
            }
        }
        private Nullable<global::System.Decimal> _COMUNA_ID;
        partial void OnCOMUNA_IDChanging(Nullable<global::System.Decimal> value);
        partial void OnCOMUNA_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal CIUDAD_ID
        {
            get
            {
                return _CIUDAD_ID;
            }
            set
            {
                if (_CIUDAD_ID != value)
                {
                    OnCIUDAD_IDChanging(value);
                    ReportPropertyChanging("CIUDAD_ID");
                    _CIUDAD_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("CIUDAD_ID");
                    OnCIUDAD_IDChanged();
                }
            }
        }
        private global::System.Decimal _CIUDAD_ID;
        partial void OnCIUDAD_IDChanging(global::System.Decimal value);
        partial void OnCIUDAD_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal REGION_ID
        {
            get
            {
                return _REGION_ID;
            }
            set
            {
                if (_REGION_ID != value)
                {
                    OnREGION_IDChanging(value);
                    ReportPropertyChanging("REGION_ID");
                    _REGION_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("REGION_ID");
                    OnREGION_IDChanged();
                }
            }
        }
        private global::System.Decimal _REGION_ID;
        partial void OnREGION_IDChanging(global::System.Decimal value);
        partial void OnREGION_IDChanged();
    
        /// <summary>
        /// No hay documentación de metadatos disponible.
        /// </summary>
        [EdmScalarPropertyAttribute(EntityKeyProperty=true, IsNullable=false)]
        [DataMemberAttribute()]
        public global::System.Decimal PAIS_ID
        {
            get
            {
                return _PAIS_ID;
            }
            set
            {
                if (_PAIS_ID != value)
                {
                    OnPAIS_IDChanging(value);
                    ReportPropertyChanging("PAIS_ID");
                    _PAIS_ID = StructuralObject.SetValidValue(value);
                    ReportPropertyChanged("PAIS_ID");
                    OnPAIS_IDChanged();
                }
            }
        }
        private global::System.Decimal _PAIS_ID;
        partial void OnPAIS_IDChanging(global::System.Decimal value);
        partial void OnPAIS_IDChanged();

        #endregion

    
    }

    #endregion

    
}
